### PR TITLE
fix(modal): change the positioning of the modal from relative to fixed

### LINKED ISSUE #360: Modal pushes content down or is pushed down by content when rendered in a page.
Make it so the Modal is `Fixed positioned` So it will always render at the top-center of the page.

### PR DESCRIPTION
**Pull request by reillz10**
This resolves #360 by making sure the Modal sits on top of all other elements in the DOM.

### CODE REVIEW

File: src/Modal/index.jsx [hunk 1]
```diff
@@ -178,30 +188,35 @@ class Modal extends React.Component {
...
-          {...(!renderHeaderCloseButton ? { ref: this.setFirstFocusableElement } : {})}
+          id="modal"
+          className={classNames(styles.modal, {
+            [styles.show]: open,
+            [styles.fade]: !open,
+            [styles['d-block']]: open,
+            [styles['is-ie11']]: this.isIE11,
+          })}
+          role="presentation"
+          onClick={e => this.close(e)}
```
Comment (AlasdairSwan) [inline src/Modal/index.jsx]: Why not just ```onClick={this.close}```?

File: src/Modal/index.jsx [hunk 2]
```diff
@@ -178,30 +188,35 @@ class Modal extends React.Component {
...
-              [styles.fade]: !open,
-              [styles['is-ie11']]: this.isIE11,
-            },
-          )}
-          role="dialog"
-          aria-modal
-          aria-labelledby={this.headerId}
-          {...(!renderHeaderCloseButton ? { tabIndex: '-1' } : {})}
-          {...(!renderHeaderCloseButton ? { ref: this.setFirstFocusableElement } : {})}
+          id="modal"
```
Comment (AlasdairSwan) [inline src/Modal/index.jsx]: Do we have to use hard-coded ids? It makes me slightly nervous given that ids need to be unique.

File: src/Modal/index.jsx [hunk 3]
```diff
@@ -178,30 +188,35 @@ class Modal extends React.Component {
...
+            aria-labelledby={this.headerId}
+            {...(!renderHeaderCloseButton ? { tabIndex: '-1' } : {})}
+            {...(!renderHeaderCloseButton ? { ref: this.setFirstFocusableElement } : {})}
+          >
+            <div className={styles['modal-content']}>
+              <div className={styles['modal-header']}>
+                <h2 className={styles['modal-title']} id={this.headerId}>{this.props.title}</h2>
+                { renderHeaderCloseButton &&
                 <Button
+                  id="paragonHeaderCloseModalButton"
```
Comment (AlasdairSwan) [inline src/Modal/index.jsx]: Do we have to use hard-coded ids? It makes me slightly nervous given that ids need to be unique.

File: src/Modal/index.jsx [hunk 4]
```diff
@@ -178,30 +188,35 @@ class Modal extends React.Component {
...
         >
-          <div className={styles['modal-content']}>
-            <div className={styles['modal-header']}>
-              <h2 className={styles['modal-title']} id={this.headerId}>{this.props.title}</h2>
-              { renderHeaderCloseButton &&
+          <div
+            className={classNames({
+              [styles['modal-dialog']]: open,
+            })}
+            styles={{ zIndex: '2000' }}
```
Comment (AlasdairSwan) [inline src/Modal/index.jsx]: Why use inline styles here instead of stylesheets? It limits the ability for sites with less sane ```z-index``` practices to customize the modal's CSS.

Comment (reillz10) [reply src/Modal/index.jsx]: sorry, i don't actually even need this at all. Good catch

File: src/Modal/index.jsx [hunk 5]
```diff
@@ -10,7 +10,9 @@ import Icon from '../Icon';
 import newId from '../utils/newId';
 import Variant from '../utils/constants';
 
-const closeModalButtonId = 'paragonCloseModalButton';
+const closeModalButtonId = newId('paragonCloseModalButton');
```
Comment (AlasdairSwan) [inline src/Modal/index.jsx]: @reillz10 to distinguish this from the ```headerCloseModalButtonId``` it may be worth updating to ```footerCloseModalButtonId```, or moving to classes so it doesn't matter the placement of the close button, just that it is a close button.
